gcc-c++11:
  script: "CI/ci-linux.sh gcc C++11"
  tags:
    - Linux

clang-c++11:
  script: "CI/ci-linux.sh clang C++11"
  tags:
    - Linux

macos-c++11:
  script: "CI/ci-mac.sh C++11"
  tags:
    - Apple

cppcheck:
  script: "CI/ci-cppcheck.sh"
  tags:
    - Linux
  artifacts:
    paths:
      - cppcheck.log

VS2019-32-bit:
  variables:
    BUILD_PLATFORM: "VS2019"
    ARCHITECTURE:   "x32"
  script: "CI\\Windows.bat"
  tags:
    - VS2019

VS2019-64-bit:
  variables:
    BUILD_PLATFORM: "VS2019"
    ARCHITECTURE:   "x64"
  script: "CI\\Windows.bat"
  tags:
    - VS2019

doc:
  script: "CI/ci-doc.sh"
  tags:
    - Linux
  artifacts:
      paths:
        - build-release/Build/share/OpenVolumeMesh/Doc/html

